name: Auto-build C/C++

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Currently no requirements.txt needed
        pip install -r requirements.txt
    
    - name: Run tests
      run: python ci_build_cpp.py

    - name: Detect log file (Success)
      run: |
          if [ -f build_log.txt ]; then
            echo "Uploading build log"
            echo "BUILD_LOG_PATH=$(pwd)/build_log.txt" >> $GITHUB_ENV
            echo "BUILD_LOG_NAME=build_log.txt" >> $GITHUB_ENV
          fi

    - name: Detect log file (Failed)
      if: failure()
      run: |
          if [ -f build_log.txt ]; then
            echo "Uploading build log"
            echo "BUILD_LOG_PATH=$(pwd)/build_log.txt" >> $GITHUB_ENV
            echo "BUILD_LOG_NAME=build_log.txt" >> $GITHUB_ENV
          fi

    - name: Upload build log (Failed)
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BUILD_LOG_NAME }}
        path: ${{ env.BUILD_LOG_PATH }}

    - name: Upload build log (Success)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BUILD_LOG_NAME }}
        path: ${{ env.BUILD_LOG_PATH }}
